const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const html = fs.readFileSync('public/index.html', 'utf8');
const code = html.slice(html.indexOf('  var recordReceipts ='), html.indexOf('  function scheduleRecordRead()'));
const storage = new Map();
const nodes = {records:{hidden:true},changes:{hidden:false},dec:{hidden:true},deadends:{hidden:true}};
let focused = true;
const badges = {};
const a = {id:'a',changes:[{at:'1',target:'first'}],decisions:['choice']};
const b = {id:'b',changes:[{at:'1',target:'first'}]};
const context = {sessions:[a,b],current:'a',document:{hidden:false,hasFocus:()=>focused,getElementById:id=>nodes[id]},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},setBadge:(id,n)=>badges[id]=n};
vm.createContext(context);vm.runInContext(code,context);
const refresh=()=>context.refreshRecordBadges();
refresh();assert.equal(badges.bRecords,2);
nodes.records.hidden=false;refresh();assert.equal(badges.bRecords,1);assert.equal(badges.bChanges,0);
nodes.changes.hidden=true;nodes.dec.hidden=false;refresh();assert.equal(badges.bRecords,0);
vm.runInContext(code,context);refresh();assert.equal(badges.bRecords,0,'read receipts survive reload');
a.changes.unshift({at:'2',target:'second'});refresh();assert.equal(badges.bChanges,1,'hidden subtab stays unread');
nodes.dec.hidden=true;nodes.changes.hidden=false;focused=false;refresh();assert.equal(badges.bChanges,1,'background window cannot read');
focused=true;refresh();assert.equal(badges.bRecords,0);
context.current='b';nodes.records.hidden=true;refresh();assert.equal(badges.bRecords,1,'sessions have separate receipts');
context.current='a';a.changes.pop();a.changes.push({at:'3',target:'replacement'});refresh();assert.equal(badges.bChanges,1,'same count replacement is new');
nodes.records.hidden=false;refresh();a.changes.push({...a.changes[0]});nodes.records.hidden=true;refresh();assert.equal(badges.bChanges,1,'duplicate entries counted separately');
assert.equal(a.changes.length,3,'reading retains records');
console.log('RECORD READ OK: read, new, reload, hidden category, background, session isolation, replacements, duplicates');
