// state.js — shared session state on disk. Zero deps.
// Every MCP server process (one per agent) writes its own session file atomically.
// The viewer (whoever holds the port) watches the dir and pushes SSE to browsers.
'use strict';
const fs = require('fs');
const path = require('path');
const os = require('os');

const ROOT = process.env.OLCHIPANEL_HOME || path.join(os.homedir(), '.olchipanel');
const SESSIONS = path.join(ROOT, 'sessions');

function ensureDirs() {
  fs.mkdirSync(SESSIONS, { recursive: true });
}

function sessionPath(id) {
  // id is generated by us (safe), but sanitize anyway
  return path.join(SESSIONS, String(id).replace(/[^A-Za-z0-9._-]/g, '_') + '.json');
}

function newSession(agentName) {
  ensureDirs();
  const now = new Date();
  const id = now.toISOString().replace(/[-:T]/g, '').slice(0, 14) + '-' + process.pid;
  const state = {
    schema: 'olchipanel.v1',
    id,
    agent: agentName || 'unknown-agent',
    name: process.env.OLCHIPANEL_NAME || '', // fixed per-config name; name_session overrides
    cwd: process.cwd(),
    started: now.toISOString(),
    updated: now.toISOString(),
    alive: true,
    goal: '',
    map: { tree: null, back: '' },
    stack: [],        // interrupt stack: [{text, resume, at}] — index 0 = latest
    decisions: [],    // [{text, kind: decision|assumption}]
    changes: [],      // [{kind, target, summary, at}] — files/commands/commits touched
    deadends: [],     // [{tried, why, at}] — failed paths, so nobody walks them twice
    pending: [],      // [{text, hot}] — what the agent needs from the human
  };
  writeSession(state);
  return state;
}

function writeSession(state) {
  ensureDirs();
  state.updated = new Date().toISOString();
  const p = sessionPath(state.id);
  const tmp = p + '.tmp';
  fs.writeFileSync(tmp, JSON.stringify(state, null, 2), 'utf8');
  fs.renameSync(tmp, p); // atomic on same volume
  return state;
}

function readAllSessions() {
  ensureDirs();
  const out = [];
  for (const f of fs.readdirSync(SESSIONS)) {
    if (!f.endsWith('.json')) continue;
    try {
      out.push(JSON.parse(fs.readFileSync(path.join(SESSIONS, f), 'utf8')));
    } catch (e) { /* torn read or bad file — skip, next SSE tick heals */ }
  }
  // newest first — parse to epoch (string compare missorts mixed "+09:00"/"Z" offsets)
  out.sort((a, b) => (Date.parse(b.started) || 0) - (Date.parse(a.started) || 0));
  return out;
}

function deleteSession(id) {
  try { fs.unlinkSync(sessionPath(id)); return true; } catch (e) { return false; }
}

// Most recent touched panel for the same project (cwd), excluding the given
// session — the handoff source a new session can inherit from.
function findPrevious(cwd, excludeId) {
  const norm = (p) => String(p || '').replace(/\\/g, '/').replace(/\/+$/, '').toLowerCase();
  const want = norm(cwd);
  return readAllSessions().find(s =>
    s.id !== excludeId && norm(s.cwd) === want && isTouched(s)) || null;
}

// "touched" = the agent actually used the panel (vs a bare handshake probe)
function isTouched(s) {
  return !!(s.goal || (s.map && s.map.tree) || (s.stack || []).length ||
    (s.decisions || []).length || (s.changes || []).length ||
    (s.deadends || []).length || (s.pending || []).length);
}

// session ids end in "-<pid>"; same-machine check whether that process still runs
function pidAlive(id) {
  const m = /-(\d+)$/.exec(String(id));
  if (!m) return null; // unknown format — don't judge
  try { process.kill(Number(m[1]), 0); return true; } catch (e) { return false; }
}

// Housekeeping at process start: repair ghost-alive sessions (owner pid dead),
// drop untouched probe sessions, expire old files. Never throws.
const KEEP_DAYS = Number(process.env.OLCHIPANEL_KEEP_DAYS || 7);
function cleanup() {
  ensureDirs();
  const cutoff = Date.now() - KEEP_DAYS * 86400e3;
  for (const f of fs.readdirSync(SESSIONS)) {
    if (!f.endsWith('.json')) continue;
    const p = path.join(SESSIONS, f);
    try {
      if (fs.statSync(p).mtimeMs < cutoff) { fs.unlinkSync(p); continue; }
      const s = JSON.parse(fs.readFileSync(p, 'utf8'));
      const owner = pidAlive(s.id);
      if (owner === false && !isTouched(s)) { fs.unlinkSync(p); continue; } // dead probe
      if (owner === false && s.alive) { s.alive = false; writeSession(s); }  // ghost repair
    } catch (e) { /* torn/corrupt handled by readAllSessions; expiry will collect it */ }
  }
}

// ---- journey tree helpers ----
function findNode(node, id) {
  if (!node) return null;
  if (node.id === id) return node;
  for (const c of node.children || []) {
    const hit = findNode(c, id);
    if (hit) return hit;
  }
  return null;
}

function clearNow(node) {
  if (!node) return;
  if (node.status === 'now') node.status = 'done';
  for (const c of node.children || []) clearNow(c);
}

module.exports = { ROOT, SESSIONS, ensureDirs, newSession, writeSession, readAllSessions,
  deleteSession, isTouched, pidAlive, cleanup, findPrevious, findNode, clearNow };
